# Generated by Django 5.1.2 on 2024-10-15 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imt_id', models.IntegerField()),
                ('nm_id', models.IntegerField()),
                ('imt_name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('subj_name', models.CharField(max_length=255)),
                ('subj_root_name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
